name: Art Booking Server CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          ls
          node -v
          cd art-booking/bacam-server
          git pull origin main
          git status
          pnpm install
          pnpm list -g --depth 0
          pnpm prisma generate 
          pnpm build 
          pm2 -v  # Check PM2 version
          pm2 restart artbooking-server
